version: "3.8"

services:
  app:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./../:/usr/src
    command: npm run start:dev

  db:
    image:  mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=events
    restart: always
    expose:
      - "3306"
    ports:
      - '2501:3306'
    healthcheck:
      test: mysqladmin -p$$POSTGRES_PASSWORD ping -h 127.0.0.1
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  backend:
    name: nestjsnetwork
